# Generated by Django 5.0.3 on 2024-04-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acr_groups_icds_temp',
            name='ICDCODE',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acr_groups_temp',
            name='ACR_GROUPID',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
    ]
