# Generated by Django 5.0.3 on 2024-05-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acr_groups_icds_temp',
            old_name='TEMP_GROUPID',
            new_name='TEMP_ACR_GROUPID',
        ),
        migrations.RenameField(
            model_name='acr_groups_rvs_temp',
            old_name='TEMP_GROUPID',
            new_name='TEMP_ACR_GROUPID',
        ),
    ]
