# Generated by Django 5.0.3 on 2024-05-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acr_groups_icds_temp',
            name='ACR_GROUPID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='acr_groups_rvs_temp',
            name='ACR_GROUPID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='acr_groups_temp',
            name='ID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acr_perrvs_rules_temp',
            name='FIXED_COPAY',
            field=models.CharField(max_length=255),
        ),
    ]
