# Generated by Django 5.0.3 on 2024-04-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acr_groups',
            name='ACTIVE',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=3),
        ),
    ]
