# Generated by Django 5.0.3 on 2024-05-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0002_alter_acr_groups_icds_temp_acr_groupid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acr_groups_icds_temp',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acr_groups_rvs_temp',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acr_groups_temp',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acr_pericd_rules_temp',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acr_perrvs_rules_temp',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
