# Generated by Django 5.0.3 on 2024-04-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0002_alter_acr_groups_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acr_perrvs_rules',
            old_name='HECK_LATERALITY',
            new_name='CHECK_LATERALITY',
        ),
    ]
