# Generated by Django 5.0.3 on 2024-05-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0003_rvs_code_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPC_CODE_MOCK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=255)),
            ],
        ),
    ]
