# Generated by Django 5.0.3 on 2024-05-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0004_spc_code_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLAIM_VALIDATION_INFOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTENT', models.TextField()),
            ],
        ),
    ]
