# Generated by Django 5.0.3 on 2024-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0008_remove_acr_groups_rvs_temp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acr_pericd_rules',
            name='ACR_GROUPID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='acr_pericd_rules_temp',
            name='ACR_GROUPID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acr_perrvs_rules',
            name='ACR_GROUPID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='acr_perrvs_rules_temp',
            name='ACR_GROUPID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
