# Generated by Django 5.0.3 on 2024-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPLMM', '0009_alter_acr_pericd_rules_acr_groupid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acr_pericd_rules',
            name='FIXED_COPAY',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acr_pericd_rules_temp',
            name='FIXED_COPAY',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acr_perrvs_rules',
            name='FIXED_COPAY',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acr_perrvs_rules_temp',
            name='FIXED_COPAY',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
